# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ADMM_Lasso <- function(X, Y, lambda, eta) {
    .Call('admmLASSO_ADMM_Lasso', PACKAGE = 'admmLASSO', X, Y, lambda, eta)
}

rcpp_hello_world <- function() {
    .Call('admmLASSO_rcpp_hello_world', PACKAGE = 'admmLASSO')
}

